#!/bin/bash

set -euo pipefail  #proper error-checking support

rm -rf $1;

mkdir -p $1/{bin,mail,inputs,tmp}

while read -r i; do
    mkdir -p $1/mail/$i;
    chown -R $i:$i $1/mail/$i; # requires script be ran as root
    chmod -R 770 $1/mail/$i;   # same 
done < valid_usernames; 

cp *.test $1/inputs/. 

#cp test-script $1/.

# build program, copy binaries into locations

make clean; 
make; 

cp mail-in $1/bin/mail-in 
cp mail-out $1/bin/mail-out

cp *.test $1/inputs/. 

